package pdf

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// ContractData represents the data needed to generate a contract PDF
type ContractData struct {
	CampaignID    string
	CampaignName  string
	Description   string
	OrganizerName string
	OrganizerID   string
	TargetAmount  float64
	Currency      string
	StartDate     time.Time
	EndDate       time.Time
	CreatedAt     time.Time
}

// Generator handles PDF generation
type Generator struct{}

// NewGenerator creates a new PDF generator
func NewGenerator() *Generator {
	return &Generator{}
}

// GenerateContract generates a charity campaign contract PDF
func (g *Generator) GenerateContract(data *ContractData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	// Title
	pdf.SetFont("Times New Roman", "B", 16)
	pdf.CellFormat(0, 15, "CHARITY CAMPAIGN CONTRACT", "", 1, "C", false, 0, "")
	pdf.Ln(5)

	// Subtitle
	pdf.SetFont("Times New Roman", "I", 12)
	pdf.CellFormat(0, 8, "Tam Sang Charity Platform", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	// Horizontal line
	pdf.SetDrawColor(0, 0, 0)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(10)

	// Contract ID section
	pdf.SetFont("Times New Roman", "B", 11)
	pdf.CellFormat(50, 8, "Contract ID:", "", 0, "L", false, 0, "")
	pdf.SetFont("Times New Roman", "", 11)
	pdf.CellFormat(0, 8, data.CampaignID, "", 1, "L", false, 0, "")

	pdf.SetFont("Times New Roman", "B", 11)
	pdf.CellFormat(50, 8, "Issue Date:", "", 0, "L", false, 0, "")
	pdf.SetFont("Times New Roman", "", 11)
	pdf.CellFormat(0, 8, data.CreatedAt.Format("02 January 2006, 15:04 MST"), "", 1, "L", false, 0, "")

	pdf.Ln(10)

	// Campaign Information
	pdf.SetFont("Times New Roman", "B", 14)
	pdf.CellFormat(0, 10, "CAMPAIGN INFORMATION", "", 1, "L", false, 0, "")
	pdf.SetDrawColor(100, 100, 100)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(5)

	// Campaign details
	addLabelValue(pdf, "Campaign Name:", data.CampaignName)
	addLabelValue(pdf, "Organizer:", data.OrganizerName)
	addLabelValue(pdf, "Organizer ID:", data.OrganizerID)
	addLabelValue(pdf, "Target Amount:", fmt.Sprintf("%.2f %s", data.TargetAmount, data.Currency))
	addLabelValue(pdf, "Start Date:", data.StartDate.Format("02 January 2006"))
	addLabelValue(pdf, "End Date:", data.EndDate.Format("02 January 2006"))

	pdf.Ln(5)
	pdf.SetFont("Times New Roman", "B", 11)
	pdf.CellFormat(0, 8, "Description:", "", 1, "L", false, 0, "")
	pdf.SetFont("Times New Roman", "", 10)
	pdf.MultiCell(0, 6, data.Description, "", "J", false)

	pdf.Ln(10)

	// Terms and Conditions
	pdf.SetFont("Times New Roman", "B", 14)
	pdf.CellFormat(0, 10, "TERMS AND CONDITIONS", "", 1, "L", false, 0, "")
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(5)

	terms := []string{
		"1. The organizer agrees to use all collected funds solely for the stated campaign purpose.",
		"2. All transactions will be recorded and auditable through the blockchain ledger.",
		"3. The organizer must provide proof of fund usage upon request.",
		"4. Any misuse of funds may result in legal action and account suspension.",
		"5. Donors' personal information will be protected according to privacy regulations.",
		"6. The platform reserves the right to suspend campaigns suspected of fraud.",
		"7. All disputes shall be resolved through arbitration in accordance with Vietnamese law.",
	}

	pdf.SetFont("Times New Roman", "", 10)
	for _, term := range terms {
		pdf.MultiCell(0, 6, term, "", "J", false)
		pdf.Ln(2)
	}

	pdf.Ln(10)

	// Signature Section
	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(0, 10, "DIGITAL SIGNATURE", "", 1, "L", false, 0, "")
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(5)

	pdf.SetFont("Arial", "I", 10)
	pdf.MultiCell(0, 6, "This contract is digitally signed using cryptographic algorithms (RSA/ECDSA) and stored on the immutable blockchain ledger. The digital signature ensures the authenticity and integrity of this document.", "", "J", false)

	pdf.Ln(10)

	// Footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(0, 10, fmt.Sprintf("Generated by Tam Sang Blockchain Service on %s", time.Now().Format(time.RFC3339)), "", 0, "C", false, 0, "")
	pdf.Ln(5)
	pdf.CellFormat(0, 10, "This is a legally binding digital contract", "", 0, "C", false, 0, "")

	// Generate PDF bytes
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}

	return buf.Bytes(), nil
}

// addLabelValue adds a label-value pair to the PDF
func addLabelValue(pdf *gofpdf.Fpdf, label, value string) {
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(50, 8, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(0, 8, value, "", 1, "L", false, 0, "")
}
